bind:
  host: 0.0.0.0
  port: 8080
logging:
  level: info
db:
  host: localhost
  port: 13306
  user: root
  password: xiaoming98
  name: ko
  max_open_conns: 200
  max_idle_conns: 10
jwt:
  secret: iXDgDaEYBzIzustW
  exp: 480
helm:
  repo:
    name: nexus
    url: http://nexus:8081/repository/helm
    username: admin
    password: admin123
kobe:
  host: kobe
  port: 8080
kotf:
  host: kotf
  port: 8080
grafana:
  host: grafana
  port: 3000
  username: admin
  password: admin
encrypt:
  multilevel: 4
  key: aaaaaaaaaaaaaaaa